server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/health_data?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 2022212917
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
